### ISSUE TITLE
An interesting work!

### ISSUE THREAD

**Issue by thaoshibe** [RobinKips/CA-GAN#3]
I've read your paper, and it drew my attentions!

1. I'm looking forward to training **codes** and the **datasets**. I emailed to the email "_contact.ia@rd.loreal.com_" (as said in the paper "available upon demand at..." but it seem like the email is not valid.

1. I would like to address some questions

- In the result video, did you reference it real-time or frame-by-frame first?
- In your framework, you just extracted 1 color (or I might say as 1 point in color space), did you try to extract the color as **color distribution**?? (Accordingly, change mse-lab to some kind of distribution loss)
- In evaluation (color accuracy evaluation, page 13), i'm wondering why we need to cluster the datasets just for target-color? Why don't we just choose any **arbitrary color**?
- And, did you try another metric for styles transfer instead of MSSIM? I just have a feeling that normally we should try L2 as L cycle loss (I have no idea) :dagger: 

Just want to thank you again for this work, hope you can answer all of my questions, I know some of them seems stupid :dancers:

**Comment by RobinKips** [comment]
Hi, 
Thanks for your message. I am surprised that your email did not reach us as we already received questions from other readers, but you were right to ask it here ! 

1. We will not be releasing the code of this model, however there is no additional trick to what is described in the paper. I would recommend to start from a Stargan implementation and modify it from there. About the data they should be available but we are waiting on clearance from the legal team. 

2.
-  The example video that we show are not real time, juste a per frame processing of the original video that was concatenated. 
- we only worked on color triplets as input, in order to focus on simplicity for the user. Using a color distribution would be more confusing in term of user experience. 
- the idea beyond clustering for the color evaluation is to make sure that we evaluate color in all the color space. Clustering ensure that we use as test colors colors that are actual lipstick colors, and not some random color that might not look like lipstick ( in practice not all colors look like a lipstick). 
- if you refer to the loss used in the cycle consistancy, we could also use LPIPS loss that would be more conventional. In practice it does not make a large difference. However l2 for this kind of tasks usually results in blurry outputs.

**Comment by thaoshibe** [comment]
Thanks for your answer!
